public class IdentifyValues {
    public static void main(String[] args) {
        byte a; // Local variables must be initialized
        short b; //Local variables must be initialized
        int c;  //Local variables must be initialized
        long d; // .............
        float e; // ............
        double f; // .........
        char g; //..........
        boolean h; //...........
        // System.out.println(h); compile time error
    }
    
}
